"""Stub adapter for testing — auto-completes workflow steps.

Writes minimal valid artifact content with configurable review outcomes.
Supports per-artifact outcome overrides for testing rework and escalation
paths.

Capability: AUTOMATIC — the run orchestrator continues without pausing.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional

from ..domain.models import (
    AdapterCapability,
    ExecutionResult,
    ExecutionStatus,
    ReviewOutcome,
)
from ..infrastructure.file_state_store import FileStateStore
from .base import AgentAdapter


class StubAdapter(AgentAdapter):
    """Auto-completes workflow steps with canned responses.

    Args:
        store: File state store for writing artifacts.
        default_outcome: Review outcome to use unless overridden.
        outcome_overrides: Map of artifact filename (or prefix) to
            ReviewOutcome. Checked before default_outcome.
    """

    def __init__(
        self,
        store: FileStateStore,
        default_outcome: ReviewOutcome = ReviewOutcome.APPROVED,
        outcome_overrides: Optional[dict[str, ReviewOutcome]] = None,
    ) -> None:
        self._store = store
        self.default_outcome = default_outcome
        self.outcome_overrides = outcome_overrides or {}
        self.call_log: list[dict[str, Any]] = []

    @property
    def name(self) -> str:
        return "stub"

    @property
    def capability(self) -> AdapterCapability:
        return AdapterCapability.AUTOMATIC

    def execute(
        self,
        task_name: str,
        artifact: str,
        template: str,
        instruction: str,
        context: dict[str, Any],
    ) -> ExecutionResult:
        """Write a minimal artifact with the configured outcome."""
        self.call_log.append(
            {
                "task_name": task_name,
                "artifact": artifact,
                "template": template,
                "instruction": instruction,
                "context": context,
            }
        )

        outcome = self._resolve_outcome(artifact)
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        is_review = "review" in artifact.lower()

        if context.get("workflow_mode") == "github":
            return self._execute_github_stub(
                task_name, artifact, outcome, is_review, now, context
            )

        if is_review:
            content = (
                f"# {artifact}\n\n"
                f"**Task**: {task_name}\n"
                f"**Date**: {now}\n"
                f"**Status**: {outcome.value}\n\n"
                f"## Summary\n\n"
                f"Auto-generated by stub adapter.\n"
            )
        elif "approval" in artifact.lower():
            content = (
                f"# Final Approval\n\n"
                f"**Task**: {task_name}\n"
                f"**Date**: {now}\n"
                f"**Status**: approved\n\n"
                f"Auto-generated by stub adapter.\n"
            )
        else:
            content = (
                f"# {artifact}\n\n"
                f"**Task**: {task_name}\n"
                f"**Date**: {now}\n\n"
                f"Auto-generated by stub adapter.\n"
            )

        self._store.write_artifact(task_name, artifact, content)

        return ExecutionResult(
            status=ExecutionStatus.COMPLETED,
            artifact_written=True,
            message=f"Stub adapter completed: {artifact}",
            review_outcome=outcome if is_review else None,
        )

    def _execute_github_stub(
        self,
        task_name: str,
        artifact: str,
        outcome: ReviewOutcome,
        is_review: bool,
        now: str,
        context: dict[str, Any],
    ) -> ExecutionResult:
        """Stub execution for GitHub workflow mode.

        Does not write file artifacts; returns the outcome directly
        since the real workflow uses GitHub PRs/reviews.
        """
        return ExecutionResult(
            status=ExecutionStatus.COMPLETED,
            artifact_written=False,
            message=f"Stub adapter completed (github mode): {artifact}",
            review_outcome=outcome if is_review else None,
        )

    def _resolve_outcome(self, artifact: str) -> ReviewOutcome:
        """Check overrides first, then fall back to default."""
        for key, outcome in self.outcome_overrides.items():
            if key in artifact:
                return outcome
        return self.default_outcome
